---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 24h
  url: https://emberstack.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  releaseName: reflector
  interval: 30m
  install:
    createNamespace: true
  chart:
    spec:
      chart: reflector
      sourceRef:
        kind: HelmRepository
        name: reflector
        namespace: reflector
      interval: 12h