---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring

spec:
  releaseName: prometheus
  targetNamespace: monitoring
  install:
    createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "62.4.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: monitoring
      interval: 12h
  values:
    prometheus:
      prometheusSpec:
        storageSpec: 
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-csi
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
    alertmanager:
      alertmanagerSpec:
        storage: 
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-csi
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
    grafana:
      persistence:
        enabled: true
        storageClassName: nfs-csi
        type: sts
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
        finalizers:
          - kubernetes.io/pvc-protection
      env:
        GF_PANELS_DISABLE_SANITIZE_HTML: "true"