apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: oracle-vault-store-pessoal
  namespace: external-secrets
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.sa-saopaulo-1.ffsq7jzbaaeua.abtxeljrnhvrdgqrpggpm5a7vtbccgesalt5mer5oteqvkak7gjfxc7bon2a
      region: sa-saopaulo-1
      auth:
        user: ocid1.user.oc1..aaaaaaaa5wcsh4c5ezax4zppd4lsc2tmbjayaytonevduefesgwdry23karq
        tenancy: ocid1.tenancy.oc1..aaaaaaaaoecb5imn4etm67dmqojtre7m57lluyxudwmoi2cs7umwolhcxtha
        secretRef:
          privatekey:
            name: oracle-secret
            key: privateKey
          fingerprint:
            name: oracle-secret
            key: fingerprint
  conditions:
    - namespaces:
        - "radar-voluntario-dev"
